# Generated by Django 4.1.7 on 2023-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_meeting", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["day", "start_hour"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="typeofmeeting",
            name="name",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily meeting"),
                    ("WEEKLY", "Weekly meeting"),
                    ("URGENT", "Urgent meeting"),
                    ("CLIENT", "Meeting with client"),
                    ("CELEBRATION", "Celebration"),
                ],
                max_length=11,
            ),
        ),
    ]
