# Generated by Django 4.1.7 on 2023-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_meeting", "0003_alter_booking_options_alter_project_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingroom",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
