# Generated by Django 4.1.7 on 2023-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_meeting", "0004_alter_meetingroom_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeofmeeting",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
